In [9]:
#importing files and libraries to process
import numpy as np
import pandas as pd
df1= pd.read_csv('Getsafedataclaimsjulaug.csv')

In [10]:
df1

,Reporting Month,Group contract,Vertical,Product Group,Product,Market,Claims Number,Customer Contract Number,Customer First Name,Customer Last Name,...,OCR / Reserve End of Period,OCR / Reserve,Claim Rejection,Rejection Reason,Fraud,Fraud Reason,Insured Object Details 1,Insured Object Details 2,Insured Object Details 3,Claims Processing Costs
0,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Basic B2C DE S...,DE,90682,I0000110386361045804001,Hamid,Salimi,...,NaN,NaN,No,NaN,No,NaN,Fahrrad,NaN,4052406314898,17
1,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Basic B2C DE S...,DE,92809,I000012714687692497001,Hanna,Nolte,...,NaN,NaN,No,NaN,No,NaN,Fahrrad,NaN,60280503,17
2,2022-08-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,89308,I0000118512201945790001,Hugues,Leydier,...,NaN,NaN,No,NaN,No,NaN,Fahrrad,Decathlon VELO VILLE ELOPS 520,000001221831,17
3,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Superior B2C D...,DE,89098,I000012081719501929001,Alexander,Schulz,...,NaN,NaN,No,anzeigepflicht_hepster,No,NaN,Fahrrad,NaN,Wow29577psei,17
4,2022-08-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,88558,I00001358112655102002,Mourad,BELEKSIR,...,NaN,NaN,No,NaN,No,NaN,Fahrrad,"WATT BOSTON MALE, X-EB 171T",PABH-2848-05,17
5,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Superior B2C D...,DE,92700,I0207011129210423936001,Severin,Reuter,...,NaN,NaN,No,NaN,No,NaN,Fahrrad,NaN,R07501B21H1033,17
6,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Basic B2C DE S...,DE,92528,I000017616746325468001,Marco,KÃ¶chy,...,NaN,NaN,No,NaN,No,NaN,E-Bike,NaN,WOW64314PVKT,17
7,2022-07-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,85165,I0000117963716062035001,Sylvie,DUGAZ,...,NaN,NaN,No,NaN,No,NaN,E-Bike,Cube,WOW97290XSGT,17
8,2022-08-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,89416,I0000120547842830153001,Matthieu,Tang,...,NaN,NaN,No,NaN,No,NaN,E-Bike,Canyon,BC2D7VBC76,17
9,2022-07-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,86755,I0000121255261963583007,Julie,Bellet,...,NaN,NaN,No,NaN,No,NaN,E-Bike,Yuba Boda boda,A9A02122,17
10,2022-08-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,88505,I00001579674363613001,Alexandre,MOINIER,...,NaN,NaN,No,NaN,No,NaN,Fahrrad,FACTOR OSTRO,OSR1CZ542215001,17

In [11]:
#checking if there are missing values present
df1= df1.style.highlight_null('orange')
df1

In [12]:
df1.to_excel('orange.xlsx')

In [13]:
df2= pd.read_excel('orange.xlsx')
#checking for duplicate in claims no.
from pandas.core.indexes.multi import duplicated
HK= df2[df2['Claims Number'].duplicated()]
dupli= HK.style.highlight_null('red')
dupli.to_excel('dupli.xlsx')

In [14]:
df3= pd.read_excel('dupli.xlsx')
df2["Duplicates_inClaimsno."] = df3["Claims Number"]
df2

,Unnamed: 0,Reporting Month,Group contract,Vertical,Product Group,Product,Market,Claims Number,Customer Contract Number,Customer First Name,...,OCR / Reserve,Claim Rejection,Rejection Reason,Fraud,Fraud Reason,Insured Object Details 1,Insured Object Details 2,Insured Object Details 3,Claims Processing Costs,Duplicates_inClaimsno.
0,0,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Basic B2C DE S...,DE,90682,I0000110386361045804001,Hamid,...,NaN,No,NaN,No,NaN,Fahrrad,NaN,4052406314898,17,NaN
1,1,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Basic B2C DE S...,DE,92809,I000012714687692497001,Hanna,...,NaN,No,NaN,No,NaN,Fahrrad,NaN,60280503,17,NaN
2,2,2022-08-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,89308,I0000118512201945790001,Hugues,...,NaN,No,NaN,No,NaN,Fahrrad,Decathlon VELO VILLE ELOPS 520,000001221831,17,NaN
3,3,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Superior B2C D...,DE,89098,I000012081719501929001,Alexander,...,NaN,No,anzeigepflicht_hepster,No,NaN,Fahrrad,NaN,Wow29577psei,17,NaN
4,4,2022-08-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,88558,I00001358112655102002,Mourad,...,NaN,No,NaN,No,NaN,Fahrrad,"WATT BOSTON MALE, X-EB 171T",PABH-2848-05,17,NaN
5,5,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Superior B2C D...,DE,92700,I0207011129210423936001,Severin,...,NaN,No,NaN,No,NaN,Fahrrad,NaN,R07501B21H1033,17,NaN
6,6,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Basic B2C DE S...,DE,92528,I000017616746325468001,Marco,...,NaN,No,NaN,No,NaN,E-Bike,NaN,WOW64314PVKT,17,NaN
7,7,2022-07-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,85165,I0000117963716062035001,Sylvie,...,NaN,No,NaN,No,NaN,E-Bike,Cube,WOW97290XSGT,17,NaN
8,8,2022-08-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,89416,I0000120547842830153001,Matthieu,...,NaN,No,NaN,No,NaN,E-Bike,Canyon,BC2D7VBC76,17,NaN
9,9,2022-07-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,86755,I0000121255261963583007,Julie,...,NaN,No,NaN,No,NaN,E-Bike,Yuba Boda boda,A9A02122,17,NaN
10,10,2022-08-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,88505,I00001579674363613001,Alexandre,...,NaN,No,NaN,No,NaN,Fahrrad,FACTOR OSTRO,OSR1CZ542215001,17,NaN

In [15]:
df2['Policy End Date']= pd.to_datetime(df2['Policy End Date'])
df2['Policy Start Date']= pd.to_datetime(df2['Policy Start Date'])
df2['Date of notification']= pd.to_datetime(df2['Date of notification'])
df2['Date of closing']= pd.to_datetime(df2['Date of closing'])
df2['Incident Event at']= pd.to_datetime(df2['Incident Event at'])

In [16]:
#checking for policy end date and start date are correct or not. if not correct then print those data
df4= df2[df2['Policy End Date'] < df2['Policy Start Date']]
df5= df4.rename(columns={"Unnamed: 0": "rowno.startfrom 0"})
df5

Empty DataFrame
Columns: [rowno.startfrom 0, Reporting Month, Group contract, Vertical, Product Group, Product , Market, Claims Number, Customer Contract Number, Customer First Name, Customer Last Name, Underwriting at, Policy Start Date, Policy End Date, Insured Sum, Deductible, Claim Type , Claim State, Incident Event at, Date of notification, Date of closing, Date of Reopening, Claims Handling Costs Start of Period, Claims Handling Costs End of Period, Change in Claims Handling Costs, Claims Payout Start of Period, Claims Payout End of Period, Change in Claims Payout, OCR / Reserve Start of Period, OCR / Reserve End of Period, OCR / Reserve, Claim Rejection, Rejection Reason , Fraud, Fraud Reason, Insured Object Details 1, Insured Object Details 2, Insured Object Details 3, Claims Processing Costs, Duplicates_inClaimsno.]
Index: []

[0 rows x 40 columns]

In [17]:
df5.to_excel('falsedatedpolicy.xlsx')

In [18]:
df5= pd.read_excel('falsedatedpolicy.xlsx')
df2["PolicyStartend_falseinfo(claims number"] = df5["Claims Number"]
df2.columns.values

array(['Unnamed: 0', 'Reporting Month', 'Group contract', 'Vertical',
       'Product Group', 'Product ', 'Market', 'Claims Number',
       'Customer Contract Number', 'Customer First Name',
       'Customer Last Name', 'Underwriting at', 'Policy Start Date',
       'Policy End Date', 'Insured Sum', 'Deductible', 'Claim Type ',
       'Claim State', 'Incident Event at', 'Date of notification',
       'Date of closing', 'Date of Reopening',
       'Claims Handling Costs Start of Period',
       'Claims Handling Costs End of Period',
       'Change in Claims Handling Costs', 'Claims Payout Start of Period',
       'Claims Payout End of Period', 'Change in Claims Payout',
       'OCR / Reserve Start of Period', 'OCR / Reserve End of Period',
       'OCR / Reserve', 'Claim Rejection', 'Rejection Reason ', 'Fraud',
       'Fraud Reason', 'Insured Object Details 1',
       'Insured Object Details 2', 'Insured Object Details 3',
       'Claims Processing Costs', 'Duplicates_inClaimsno.',
       'PolicyStartend_falseinfo(claims number'], dtype=object)

In [19]:
df6= df2[df2['Insured Sum'] < df2['Claims Payout Start of Period']]
df6

Empty DataFrame
Columns: [Unnamed: 0, Reporting Month, Group contract, Vertical, Product Group, Product , Market, Claims Number, Customer Contract Number, Customer First Name, Customer Last Name, Underwriting at, Policy Start Date, Policy End Date, Insured Sum, Deductible, Claim Type , Claim State, Incident Event at, Date of notification, Date of closing, Date of Reopening, Claims Handling Costs Start of Period, Claims Handling Costs End of Period, Change in Claims Handling Costs, Claims Payout Start of Period, Claims Payout End of Period, Change in Claims Payout, OCR / Reserve Start of Period, OCR / Reserve End of Period, OCR / Reserve, Claim Rejection, Rejection Reason , Fraud, Fraud Reason, Insured Object Details 1, Insured Object Details 2, Insured Object Details 3, Claims Processing Costs, Duplicates_inClaimsno., PolicyStartend_falseinfo(claims number]
Index: []

[0 rows x 41 columns]

In [20]:
df6= df6.rename(columns={"Unnamed: 0": "Insured_sum_payout_issue_in column"})

In [21]:
df6.to_excel('datedif.xlsx')

In [22]:
df6= pd.read_excel('datedif.xlsx')

In [23]:
df2["Insured_sum_payout_issue_in column"] = df6["Insured_sum_payout_issue_in column"]

In [24]:
df7= df2[df2['Incident Event at'] > df2['Date of notification']]

In [25]:
df7.to_excel('datedDON-Incedent.xlsx')

In [26]:
df7= df7.rename(columns={"Unnamed: 0": "the row at which the Incident event is> DON"})
df7.to_excel('datedDON-Incedent.xlsx')

In [27]:
df7= pd.read_excel('datedDON-Incedent.xlsx')
df2["the claim at which the Incident event is> DON"] = df7["Claims Number"]
df7

,Unnamed: 0,the row at which the Incident event is> DON,Reporting Month,Group contract,Vertical,Product Group,Product,Market,Claims Number,Customer Contract Number,...,Rejection Reason,Fraud,Fraud Reason,Insured Object Details 1,Insured Object Details 2,Insured Object Details 3,Claims Processing Costs,Duplicates_inClaimsno.,PolicyStartend_falseinfo(claims number,Insured_sum_payout_issue_in column
0,1,1,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Basic B2C DE S...,DE,92809,I000012714687692497001,...,NaN,No,NaN,Fahrrad,NaN,60280503,17,NaN,NaN,NaN
1,3,3,2022-08-01 00:00:00,check24,e-bike / bike,kasko,Fahrrad und E-Bike Versicherung Superior B2C D...,DE,89098,I000012081719501929001,...,anzeigepflicht_hepster,No,NaN,Fahrrad,NaN,Wow29577psei,17,NaN,NaN,NaN
2,7,7,2022-07-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,85165,I0000117963716062035001,...,NaN,No,NaN,E-Bike,Cube,WOW97290XSGT,17,NaN,NaN,NaN
3,8,8,2022-08-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,89416,I0000120547842830153001,...,NaN,No,NaN,E-Bike,Canyon,BC2D7VBC76,17,NaN,NaN,NaN
4,9,9,2022-07-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,86755,I0000121255261963583007,...,NaN,No,NaN,E-Bike,Yuba Boda boda,A9A02122,17,NaN,NaN,NaN
5,10,10,2022-08-01 00:00:00,hepster,e-bike / bike,kasko,AVB Bike / E-Bike Schutz 2022 B2C FR,FR,88505,I00001579674363613001,...,NaN,No,NaN,Fahrrad,FACTOR OSTRO,OSR1CZ542215001,17,NaN,NaN,NaN

In [28]:
df2= df2.style.highlight_null('orange')

In [29]:
df2.to_excel('finalform.xlsx')

In [30]:
df2