In [37]:
#Importing libraries and the file to be processed
import numpy as np
import pandas as pd
df1= pd.read_csv('Helvetia-tpa(B).csv')

In [38]:
#adding values to Schadenbetrag bezahlt (SB bereits abgezogen) by difference of TPA Rechnungbetrag and Selbstbehalt
df1['Schadenbetrag bezahlt (SB bereits abgezogen)'] = df1['TPA Rechnungbetrag']- df1['Selbstbehalt']

In [39]:
df1

,Verwendungszweck,Zendesk Ticket,Provider-ID,Schadennummer,von TPA erhalten,Risikobelegenheit,Sitz des Händlers,Grund des Rückerhaltes,Produktbezeichnung,Product Code,...,Schadenbetrag bezahlt (SB bereits abgezogen),Status,Ablehnungsgrund,Datum geschlossen,Versicherungssumme,Selbstbehalt,Eingereichter Schadenbetrag (für 1 eindeutig Zendesk Ticket),Schadenbearbeitungskosten,insurance_provider,Fallart
0,NaN,64039,1001955,64039I000012392595140720001,NaN,DE,NaN,NaN,Smartphone/Tablertversicherung,115,...,447.00,none_-_status_schadenverlauf,NaN,2021-12-07 00:00:00,"1000,00",100,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
1,NaN,64350,1001965,64350I0000110243432350520001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,83,...,334.00,none_-_status_schadenverlauf,NaN,2021-12-13 00:00:00,"500,00",55,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
2,NaN,64410,1001967,64410I000019282087480120001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,84,...,314.00,none_-_status_schadenverlauf,NaN,2021-12-13 00:00:00,"750,00",75,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
3,NaN,65026,1001976,65026I000012543930550720003,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,96,...,314.00,none_-_status_schadenverlauf,NaN,2021-12-20 00:00:00,"750,00",75,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
4,NaN,65702,1001999,65702I0000110229368980920001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,85,...,99.00,none_-_status_schadenverlauf,NaN,2021-12-30 00:00:00,"1000,00",100,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
5,NaN,65706,1002000,65706I000014191835020121001,NaN,DE,NaN,NaN,Smartphone/Tablertversicherung,85,...,154.46,übernommen,NaN,2021-12-30 00:00:00,"1000,00",100,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
6,NaN,66116,1002012,66116I0000120155394540220001,NaN,DE,NaN,NaN,Smartphone/Tablertversicherung,98,...,259.00,none_-_status_schadenverlauf,NaN,2022-01-04 00:00:00,"1500,00",120,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
7,NaN,66493,1002024,66493I000019364944062762001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,103,...,807.00,none_-_status_schadenverlauf,NaN,2022-01-10 00:00:00,"1000,00",100,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
8,NaN,67917,1002079,67917I000016171026401941002,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,110,...,662.37,none_-_status_schadenverlauf,NaN,2022-02-02 00:00:00,"1500,00",120,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
9,NaN,68355,1002065,68355I000018013666955325003,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,82,...,73.85,none_-_status_schadenverlauf,NaN,2022-01-27 00:00:00,"250,00",35,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
10,NaN,69491,1002086,69491I000017621466080721001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,91,...,18.24,none_-_status_schadenverlauf,NaN,2022-02-07 00:00:00,"1000,00",100,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
11,NaN,69529,1002090,69529I0000113627917011120001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,111,...,502.61,none_-_status_schadenverlauf,NaN,2022-02-08 00:00:00,"2000,00",150,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
12,NaN,69796,1002096,69796I0000119374292590520001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,90,...,481.17,none_-_status_schadenverlauf,NaN,2022-02-10 00:00:00,"750,00",75,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
13,NaN,69799,1002095,69799I000014369668440221001,NaN,DE,NaN,NaN,Smartphone/Tablertversicherung,98,...,320.33,none_-_status_schadenverlauf,NaN,2022-02-10 00:00:00,"1500,00",120,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
14,NaN,69849,1002098,69849I0000118324807510621001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,89,...,184.00,none_-_status_schadenverlauf,NaN,2022-02-10 00:00:00,"500,00",55,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
15,NaN,69923,1002099,69923I000016741416050619002,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,114,...,174.37,none_-_status_schadenverlauf,NaN,2022-02-11 00:00:00,"750,00",75,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
16,NaN,70871,1002121,70871I0000113667438300920001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,95,...,145.78,none_-_status_schadenverlauf,NaN,2022-02-21 00:00:00,"500,00",55,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
17,NaN,70939,1002118,70939I0000111816185550720001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,83,...,151.54,none_-_status_schadenverlauf,NaN,2022-02-21 00:00:00,"500,00",55,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
18,NaN,71073,1002123,71073I0000113108052150720001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,108,...,457.50,none_-_status_schadenverlauf,NaN,2022-02-22 00:00:00,"750,00",75,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
19,NaN,71265,1002128,71265I0000112853148447742004,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,101,...,141.52,none_-_status_schadenverlauf,NaN,2022-02-24 00:00:00,"500,00",55,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
20,NaN,71488,1002130,71488I000015024516410421002,NaN,DE,NaN,NaN,Smartphone/Tablertversicherung,92,...,349.34,none_-_status_schadenverlauf,NaN,2022-02-25 00:00:00,"1500,00",120,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
21,NaN,74439,1002185,74439I000015142569741120001,hepster reguliert,DE,DE,NaN,Smartphone/Tablertversicherung,91,...,269.00,none_-_status_schadenverlauf,NaN,2022-03-23 00:00:00,"1000,00",100,NaN,NaN,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
22,NaN,80677,1002267,80677I0000116480061691120001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,86,...,699.00,none_-_status_schadenverlauf,NaN,2022-05-10 00:00:00,"1500,00",120,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
23,NaN,81251,1002371,81251I000015038461057020001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,98,...,1209.00,none_-_status_schadenverlauf,NaN,2022-05-17 00:00:00,"1500,00",120,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
24,NaN,81319,1002273,81319I000018131167900520001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,102,...,244.00,none_-_status_schadenverlauf,NaN,2022-05-16 00:00:00,"750,00",75,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
25,NaN,81512,1002369,81512I000012436771590621001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,95,...,144.00,none_-_status_schadenverlauf,NaN,2022-07-07 00:00:00,"500,00",55,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
26,NaN,82165,1002288,82165I0000116050145920121001,NaN,DE,NaN,NaN,Smartphone/Tablertversicherung,84,...,194.00,none_-_status_schadenverlauf,NaN,2022-05-23 00:00:00,"750,00",75,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
27,NaN,84832,1002324,84832I0000119588725752516001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,89,...,334.00,none_-_status_schadenverlauf,NaN,2022-06-13 00:00:00,"500,00",55,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
28,NaN,85154,1002325,85154I0000119983098012896001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,104,...,929.00,none_-_status_schadenverlauf,NaN,2022-06-14 00:00:00,"1500,00",120,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
29,NaN,86864,1002343,86864I000018988360970920001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,85,...,169.00,none_-_status_schadenverlauf,NaN,2022-06-27 00:00:00,"1000,00",100,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
30,NaN,87655,1002365,87655I000011895739956179001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,104,...,348.00,none_-_status_schadenverlauf,NaN,2022-07-05 00:00:00,"1500,00",120,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
31,NaN,88030,1002358,88030I0000113735990881220001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,83,...,124.00,none_-_status_schadenverlauf,NaN,2022-07-05 00:00:00,"500,00",55,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
32,NaN,88438,1002367,88438I000015375590440820001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,104,...,269.00,none_-_status_schadenverlauf,NaN,2022-07-06 00:00:00,"1500,00",120,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
33,NaN,88926,1002378,88926I000013374315690521001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,100,...,94.00,none_-_status_schadenverlauf,NaN,2022-07-13 00:00:00,"250,00",35,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
34,NaN,89102,1002376,89102I0000120381885230720001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,96,...,524.00,none_-_status_schadenverlauf,NaN,2022-07-11 00:00:00,"750,00",75,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
35,NaN,89125,1002377,89125I000015795529582566001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,86,...,1219.00,none_-_status_schadenverlauf,NaN,2022-07-13 00:00:00,"1500,00",120,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
36,NaN,89170,1002372,89170I000014622402540720001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,91,...,359.00,none_-_status_schadenverlauf,NaN,2022-07-11 00:00:00,"1000,00",100,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
37,NaN,89202,1002373,89202I0000110738826290920001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,83,...,314.00,none_-_status_schadenverlauf,NaN,2022-07-11 00:00:00,"500,00",55,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
38,NaN,89254,1002374,89254I0000112809779321220001,hepster reguliert,DE,DE,NaN,Smartphone/Tablertversicherung,84,...,194.00,none_-_status_schadenverlauf,NaN,2022-07-11 00:00:00,"750,00",75,NaN,NaN,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
39,NaN,89635,1002384,89635I000014204045570121001,hepster reguliert,DE,DE,NaN,Smartphone/Tablertversicherung,102,...,418.00,none_-_status_schadenverlauf,NaN,2022-07-15 00:00:00,"750,00",75,NaN,NaN,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
40,NaN,89772,1002382,89772I0000111235022942777001,hepster reguliert,DE,NaN,NaN,Smartphone/Tablertversicherung,98,...,1029.00,none_-_status_schadenverlauf,NaN,2022-07-15 00:00:00,"1500,00",120,NaN,NaN,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
41,NaN,89838,1002381,89838I000014491052080620003,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,115,...,239.00,none_-_status_schadenverlauf,NaN,2022-07-14 00:00:00,"1000,00",100,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
42,NaN,89839,1002380,89839I000019878251242433001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,83,...,324.00,none_-_status_schadenverlauf,NaN,2022-07-14 00:00:00,"500,00",55,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
43,NaN,90470,1002392,90470I000017862515578906002,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,85,...,499.00,none_-_status_schadenverlauf,NaN,2022-07-19 00:00:00,"1000,00",100,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
44,NaN,90535,1002389,90535I0000114775220630820001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,96,...,394.00,none_-_status_schadenverlauf,NaN,2022-07-19 00:00:00,"750,00",75,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
45,NaN,90756,1002391,90756I0000117669369597143001,hepster reguliert,DE,DE,NaN,Smartphone/Tablertversicherung,93,...,569.00,none_-_status_schadenverlauf,NaN,2022-07-20 00:00:00,"2000,00",150,NaN,NaN,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden
46,NaN,90900,1002393,90900I000014302135530121001,NaN,DE,DE,NaN,Smartphone/Tablertversicherung,84,...,224.00,none_-_status_schadenverlauf,NaN,2022-07-21 00:00:00,"750,00",75,NaN,7.0,Helvetia Schweizerische Versicherungsgesellsch...,schaden__auszahlung__schaden

In [40]:
#checking for duplicates in zendesk no.
from pandas.core.indexes.multi import duplicated
HK= df1[df1['Zendesk Ticket'].duplicated()]
df2= HK.style.highlight_null('red')
df2.to_excel('Dupli.xlsx')

In [41]:
df3= pd.read_excel('Dupli.xlsx')

In [42]:
df1["duplcate_zendesk_list"]=  df3["Zendesk Ticket"]

In [43]:
#converting datatype of Risikostart and vertragsbeginn to date_time
df1['Risikostart']= pd.to_datetime(df1['Risikostart'])
df1['Risikoende']= pd.to_datetime(df1['Risikoende'])
df1['Vertragsbeginn gem. Zertifikat']= pd.to_datetime(df1['Vertragsbeginn gem. Zertifikat'])
df1['Vertragsende gem. Zertifikat/voraussichtliches Vertragsende']= pd.to_datetime(df1['Vertragsende gem. Zertifikat/voraussichtliches Vertragsende'])

In [44]:
df1['Risikostart']= pd.to_datetime(df1['Risikostart'])
df1['Risikoende']= pd.to_datetime(df1['Risikoende'])
df1['Vertragsbeginn gem. Zertifikat']= pd.to_datetime(df1['Vertragsbeginn gem. Zertifikat'])
df1['Vertragsende gem. Zertifikat/voraussichtliches Vertragsende']= pd.to_datetime(df1['Vertragsende gem. Zertifikat/voraussichtliches Vertragsende'])


df1['DifferenceRisk'] = df1['Risikoende']-df1['Risikostart']
df1['Differencevertrag'] = df1['Vertragsende gem. Zertifikat/voraussichtliches Vertragsende']-df1['Vertragsbeginn gem. Zertifikat']

In [45]:
#checking if there are any errors in difference of risks and vetrags dates
df1[df1['DifferenceRisk']<'0 days']
df1[df1['Differencevertrag']<'0 days']

Empty DataFrame
Columns: [Verwendungszweck, Zendesk Ticket, Provider-ID, Schadennummer, von TPA erhalten, Risikobelegenheit, Sitz des Händlers, Grund des Rückerhaltes, Produktbezeichnung, Product Code, Product Details, Nachname_VN, Vorname_VN, Zertifikatsnummer, Vertragstyp, Verkaufspartnerfirma, Hersteller, Modell, IMEI/Seriennummer, Kaufdatum des Gegenstandes, Datum Policenübermittlung, Vertragsbeginn gem. Zertifikat, Vertragsende gem. Zertifikat/voraussichtliches Vertragsende, Versicherungsdauer in Tagen, Versicherungsdauer in Monaten, Risikostart, Risikoende, Risikodauer, Vertragserneuerung, Schadenmeldedatum, Schadendatum, Schadentyp aus Schadenmeldung, Schadentyp aus Schadenprotokoll, Abrechnung durch, Datum Schadenfall bezahlt, TPA Rechnungbetrag, Schadenbetrag bezahlt (SB bereits abgezogen), Status, Ablehnungsgrund, Datum geschlossen, Versicherungssumme, Selbstbehalt, Eingereichter Schadenbetrag (für 1 eindeutig Zendesk Ticket), Schadenbearbeitungskosten, insurance_provider, Fallart, duplcate_zendesk_list, DifferenceRisk, Differencevertrag]
Index: []

[0 rows x 49 columns]

In [46]:
my_series = pd.Series(df1.DifferenceRisk)
df1['DifferenceRisk'] = my_series.to_frame()
print(df1['DifferenceRisk'])
print(type(df1['DifferenceRisk']))
my_series = pd.Series(df1.Differencevertrag)
df1['Differencevertrag'] = my_series.to_frame()
print(df1['Differencevertrag'])
print(type(df1['Differencevertrag']))

0     608 days
1    1095 days
2     731 days
3     730 days
4     730 days
5     730 days
6     731 days
7     730 days
8     242 days
9     365 days
10    730 days
11    699 days
12   1095 days
13    730 days
14    365 days
15   1096 days
16    730 days
17    730 days
18    789 days
19    730 days
20    730 days
21    730 days
22    730 days
23    730 days
24    730 days
25    730 days
26    730 days
27    365 days
28    730 days
29    730 days
30    730 days
31    730 days
32    730 days
33    730 days
34    730 days
35    365 days
36   1095 days
37   1095 days
38    730 days
39    730 days
40    316 days
41    822 days
42    365 days
43    365 days
44    730 days
45    365 days
46    730 days
Name: DifferenceRisk, dtype: timedelta64[ns]
<class 'pandas.core.series.Series'>
0     607 days 12:04:00
1    1094 days 05:04:00
2     730 days 09:24:00
3     729 days 07:55:00
4     729 days 06:08:00
5     729 days 10:58:00
6     730 days 01:52:00
7     729 days 09:06:00
8     241 days 06:14:00
9     364 days 00:07:00
10    729 days 13:58:00
11    698 days 07:59:00
12   1094 days 08:30:00
13    729 days 09:15:00
14    364 days 13:15:00
15   1095 days 08:56:00
16    729 days 06:11:00
17    729 days 09:57:00
18    788 days 08:33:00
19    730 days 00:00:00
20    729 days 10:22:00
21    729 days 06:22:00
22    729 days 08:35:00
23    729 days 06:49:00
24    729 days 09:55:00
25    729 days 03:07:00
26    729 days 12:08:00
27    364 days 02:25:00
28    729 days 04:07:00
29    729 days 02:49:00
30    729 days 07:19:00
31    730 days 00:00:00
32    729 days 11:46:00
33    729 days 14:05:00
34    729 days 06:47:00
35    364 days 09:05:00
36   1094 days 12:22:00
37   1094 days 10:44:00
38    729 days 13:50:00
39    729 days 16:06:00
40    315 days 03:54:00
41    821 days 14:54:00
42    364 days 09:29:00
43    364 days 12:38:00
44    729 days 07:45:00
45    364 days 13:40:00
46    729 days 01:26:00
Name: Differencevertrag, dtype: timedelta64[ns]
<class 'pandas.core.series.Series'>

In [47]:
risk= pd.DataFrame(df1['DifferenceRisk'].dt.days)
vertrag= pd.DataFrame(df1['Differencevertrag'].dt.days)

In [48]:
def change_color(value):
  color= 'red' if value <0 else 'green'
  return 'color: %s' %color

In [49]:
# If dates difference are negative then the 
df2= risk.style.applymap(change_color)
df3= vertrag.style.applymap(change_color)
df2.to_excel('Rdifference.xlsx')
df3.to_excel('Vdifference.xlsx')
df2

In [50]:
df3

In [51]:
df2= pd.read_excel('Rdifference.xlsx')
df3= pd.read_excel('Vdifference.xlsx')
df1["RDifferenceRisk"] = df2["DifferenceRisk"]
df1["VDifferenceRisk"] = df3["Differencevertrag"]

In [52]:
df7= df1['Status'].replace(['none_-_status_schadenverlauf'],'übernommen')
df7 = pd.DataFrame([x for x in df7])
df7.columns =['StatusUPD']
df7
df7.to_excel('status_Upd.xlsx')

In [53]:
df8= pd.read_excel('status_Upd.xlsx')
df1.drop(["Status"], axis = 1, inplace = True)
df1["Status"] = df8["StatusUPD"]
df1.to_excel('finalform_helvetia_tpa(B).xlsx')

In [54]:
df1= df1.style.highlight_null('orange')
df1.to_excel('finalHelvetiatpa.xlsx')
df1