In [24]:
import numpy as np
import pandas as pd

In [25]:
# imported libraries and now importing the file
df1= pd.read_csv('newlvclaim.csv')

In [26]:
#converting the datatype of dates in our data to data_time data type
df1['Risikostart']= pd.to_datetime(df1['Risikostart'])
df1['Risikoende']= pd.to_datetime(df1['Risikoende'])
df1['Vertragsbeginn gem. Zertifikat']= pd.to_datetime(df1['Vertragsbeginn gem. Zertifikat'])
df1['Vertragsende gem. Zertifikat/voraussichtliches Vertragsende']= pd.to_datetime(df1['Vertragsende gem. Zertifikat/voraussichtliches Vertragsende'])

In [27]:
df1['Risikostart']= pd.to_datetime(df1['Risikostart'])
df1['Risikoende']= pd.to_datetime(df1['Risikoende'])
df1['Vertragsbeginn gem. Zertifikat']= pd.to_datetime(df1['Vertragsbeginn gem. Zertifikat'])
df1['Vertragsende gem. Zertifikat/voraussichtliches Vertragsende']= pd.to_datetime(df1['Vertragsende gem. Zertifikat/voraussichtliches Vertragsende'])

# Calculating the difference b/w the following dates. If negatives difference is present then we have an error
df1['DifferenceRisk'] = df1['Risikoende']-df1['Risikostart']
df1['Differencevertrag'] = df1['Vertragsende gem. Zertifikat/voraussichtliches Vertragsende']-df1['Vertragsbeginn gem. Zertifikat']

In [28]:
df4= df1[df1['DifferenceRisk']<'0 days']
df4.to_excel('DifferenceRisk.xlsx')

In [29]:
df4

Empty DataFrame
Columns: [Verwendungszweck, Zendesk Ticket, Provider-ID, Schadennummer, von TPA erhalten, Risikobelegenheit, Sitz des Händlers, Grund des Rückerhaltes von TPA, Produktbezeichnung, Product Code, Product Details, Nachname_VN, Vorname_VN, Zertifikatsnummer, Vertragstyp, Verkaufspartnerfirma, Hersteller, Modell, IMEI/Seriennummer, Kaufdatum des Gegenstandes, Datum Policenübermittlung, Vertragsbeginn gem. Zertifikat, Vertragsende gem. Zertifikat/voraussichtliches Vertragsende, Versicherungsdauer in Tagen, Versicherungsdauer in Monaten, Risikostart, Risikoende, Risikodauer, Vertragserneuerung, Schadenmeldedatum, Schadendatum, Schadentyp aus Schadenmeldung, Schadentyp aus Schadenprotokoll, Abrechnung durch, Datum Schadenfall bezahlt, TPA Rechnungbetrag, Schadenbetrag bezahlt (SB bereits abgezogen), Status, Ablehnungsgrund, Datum geschlossen, Versicherungssumme, Selbstbehalt, Eingereichter Schadenbetrag (für 1 eindeutig Zendesk Ticket), Schadenbearbeitungskosten, insurance_provider, Fallart, Zendesk Ticket Status, Auszahlung_Datev, DifferenceRisk, Differencevertrag]
Index: []

[0 rows x 50 columns]

In [30]:
df7= pd.read_excel('DifferenceRisk.xlsx')
df1["Diff_risk_end_start_Error(zendesk)"] = df7["Zendesk Ticket"]
df1

,Verwendungszweck,Zendesk Ticket,Provider-ID,Schadennummer,von TPA erhalten,Risikobelegenheit,Sitz des Händlers,Grund des Rückerhaltes von TPA,Produktbezeichnung,Product Code,...,Selbstbehalt,Eingereichter Schadenbetrag (für 1 eindeutig Zendesk Ticket),Schadenbearbeitungskosten,insurance_provider,Fallart,Zendesk Ticket Status,Auszahlung_Datev,DifferenceRisk,Differencevertrag,Diff_risk_end_start_Error(zendesk)
0,NaN,91967,NaN,91967I006132133782354482002,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,0,NaN,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN
1,NaN,90465,NaN,90465I0061315389811679996004,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,0,NaN,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN
2,NaN,91860,NaN,91860I0061318335371160356032,NaN,DE,DE,NaN,Restschuld,NaN,...,0,NaN,NaN,LV 1871 Private Assurance AG,NaN,hold,NaN,915 days,1095 days,NaN
3,NaN,95749,NaN,95749I0061319129274253642002,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,0,3159.73,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN
4,NaN,90424,NaN,90424I0000118335371164679018,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,0,2888.47,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,S-I0000114781307090721080/57801,57801,NaN,57801I0000114781307090721080,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,0,1041.24,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,closed,-1041.24,915 days,1095 days,NaN
144,EREF+4134253100-0000001KREF+4134253100SVWZ+RNr...,55916,NaN,55916I000012953919911219002,hepster reguliert,DE,NaN,NaN,Restschuld,NaN,...,0,NaN,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,closed,-938.82,915 days,1095 days,NaN
145,NaN,81287,NaN,81287I0000120496743081119004,NaN,DE,NaN,NaN,Restschuld,NaN,...,0,NaN,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,hold,NaN,915 days,1095 days,NaN
146,NaN,93461,NaN,93461I0000114542009321119006,NaN,DE,DE,NaN,Restschuld,NaN,...,0,NaN,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,hold,NaN,915 days,1095 days,NaN
147,NaN,78815,NaN,78815I0000120907639951019018,hepster reguliert,DE,NaN,NaN,Restschuld,NaN,...,0,NaN,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,hold,NaN,915 days,1095 days,NaN

In [31]:
df5= df1[df1['Differencevertrag']<'0 days']
df5.to_excel('Differencevertrag.xlsx')
df8= pd.read_excel('Differencevertrag.xlsx')
df1["Diff_vertrag_end_start_Error(zendesk)"] = df8["Zendesk Ticket"]
df1

,Verwendungszweck,Zendesk Ticket,Provider-ID,Schadennummer,von TPA erhalten,Risikobelegenheit,Sitz des Händlers,Grund des Rückerhaltes von TPA,Produktbezeichnung,Product Code,...,Eingereichter Schadenbetrag (für 1 eindeutig Zendesk Ticket),Schadenbearbeitungskosten,insurance_provider,Fallart,Zendesk Ticket Status,Auszahlung_Datev,DifferenceRisk,Differencevertrag,Diff_risk_end_start_Error(zendesk),Diff_vertrag_end_start_Error(zendesk)
0,NaN,91967,NaN,91967I006132133782354482002,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,NaN,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN,NaN
1,NaN,90465,NaN,90465I0061315389811679996004,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,NaN,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN,NaN
2,NaN,91860,NaN,91860I0061318335371160356032,NaN,DE,DE,NaN,Restschuld,NaN,...,NaN,NaN,LV 1871 Private Assurance AG,NaN,hold,NaN,915 days,1095 days,NaN,NaN
3,NaN,95749,NaN,95749I0061319129274253642002,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,3159.73,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN,NaN
4,NaN,90424,NaN,90424I0000118335371164679018,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,2888.47,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,S-I0000114781307090721080/57801,57801,NaN,57801I0000114781307090721080,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,1041.24,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,closed,-1041.24,915 days,1095 days,NaN,NaN
144,EREF+4134253100-0000001KREF+4134253100SVWZ+RNr...,55916,NaN,55916I000012953919911219002,hepster reguliert,DE,NaN,NaN,Restschuld,NaN,...,NaN,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,closed,-938.82,915 days,1095 days,NaN,NaN
145,NaN,81287,NaN,81287I0000120496743081119004,NaN,DE,NaN,NaN,Restschuld,NaN,...,NaN,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,hold,NaN,915 days,1095 days,NaN,NaN
146,NaN,93461,NaN,93461I0000114542009321119006,NaN,DE,DE,NaN,Restschuld,NaN,...,NaN,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,hold,NaN,915 days,1095 days,NaN,NaN
147,NaN,78815,NaN,78815I0000120907639951019018,hepster reguliert,DE,NaN,NaN,Restschuld,NaN,...,NaN,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,hold,NaN,915 days,1095 days,NaN,NaN

In [32]:
#checking for duplicates for zendesk ticket no. 
from pandas.core.indexes.multi import duplicated
HK= df1[df1['Zendesk Ticket'].duplicated()]
dupli= HK.style.highlight_null('red')
dupli

In [33]:
dupli.to_excel('dupli.xlsx')

df10= pd.read_excel('dupli.xlsx')
df1["Duplicate_zendesk_in table"] = df10["Zendesk Ticket"]
df1

,Verwendungszweck,Zendesk Ticket,Provider-ID,Schadennummer,von TPA erhalten,Risikobelegenheit,Sitz des Händlers,Grund des Rückerhaltes von TPA,Produktbezeichnung,Product Code,...,Schadenbearbeitungskosten,insurance_provider,Fallart,Zendesk Ticket Status,Auszahlung_Datev,DifferenceRisk,Differencevertrag,Diff_risk_end_start_Error(zendesk),Diff_vertrag_end_start_Error(zendesk),Duplicate_zendesk_in table
0,NaN,91967,NaN,91967I006132133782354482002,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN,NaN,79710.0
1,NaN,90465,NaN,90465I0061315389811679996004,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN,NaN,81867.0
2,NaN,91860,NaN,91860I0061318335371160356032,NaN,DE,DE,NaN,Restschuld,NaN,...,NaN,LV 1871 Private Assurance AG,NaN,hold,NaN,915 days,1095 days,NaN,NaN,71320.0
3,NaN,95749,NaN,95749I0061319129274253642002,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN,NaN,NaN
4,NaN,90424,NaN,90424I0000118335371164679018,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,NaN,915 days,1095 days,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,S-I0000114781307090721080/57801,57801,NaN,57801I0000114781307090721080,hepster reguliert,DE,DE,NaN,Restschuld,NaN,...,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,closed,-1041.24,915 days,1095 days,NaN,NaN,NaN
144,EREF+4134253100-0000001KREF+4134253100SVWZ+RNr...,55916,NaN,55916I000012953919911219002,hepster reguliert,DE,NaN,NaN,Restschuld,NaN,...,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,closed,-938.82,915 days,1095 days,NaN,NaN,NaN
145,NaN,81287,NaN,81287I0000120496743081119004,NaN,DE,NaN,NaN,Restschuld,NaN,...,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,hold,NaN,915 days,1095 days,NaN,NaN,NaN
146,NaN,93461,NaN,93461I0000114542009321119006,NaN,DE,DE,NaN,Restschuld,NaN,...,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,hold,NaN,915 days,1095 days,NaN,NaN,NaN
147,NaN,78815,NaN,78815I0000120907639951019018,hepster reguliert,DE,NaN,NaN,Restschuld,NaN,...,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,hold,NaN,915 days,1095 days,NaN,NaN,NaN

In [34]:
df1.to_excel('nextstep.xlsx')

In [35]:
df12= pd.read_excel('nextstep.xlsx')

In [36]:
type(df12['Versicherungssumme'])

pandas.core.series.Series

In [37]:
#converting versicherungsumme and schaden betrag bezahlt to dataframe for mathematical operations
my_series = pd.Series(df12.Versicherungssumme)
df12['Versicherungssumme'] = my_series.to_frame()
print(df12['Versicherungssumme'])
print(type(df12['Versicherungssumme']))
sum= pd.DataFrame(df12['Versicherungssumme'].str)

my_series = pd.Series(df12.Versicherungssumme)
df12['Schadenbetrag bezahlt (SB bereits abgezogen)'] = my_series.to_frame()
print(df12['Schadenbetrag bezahlt (SB bereits abgezogen)'])
print(type(df12['Schadenbetrag bezahlt (SB bereits abgezogen)']))
schaden= pd.DataFrame(df12['Schadenbetrag bezahlt (SB bereits abgezogen)'].str)

0      3500,00
1      3500,00
2      3500,00
3      3500,00
4      3500,00
        ...
143    3500,00
144    3000,00
145    3000,00
146    3000,00
147    4000,00
Name: Versicherungssumme, Length: 148, dtype: object
<class 'pandas.core.series.Series'>
0      3500,00
1      3500,00
2      3500,00
3      3500,00
4      3500,00
        ...
143    3500,00
144    3000,00
145    3000,00
146    3000,00
147    4000,00
Name: Schadenbetrag bezahlt (SB bereits abgezogen), Length: 148, dtype: object
<class 'pandas.core.series.Series'>

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:684: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  data = list(data)

In [38]:
def change_color(value):
  color= 'red' if value <0 else 'green'
  return 'color: %s' %color

In [39]:
df12['Schadenmeldedatum']= pd.to_datetime(df12['Schadenmeldedatum'])
df12['Schadendatum']= pd.to_datetime(df12['Schadendatum'])

In [41]:
df13= df12[df12['Schadenmeldedatum'] < df12['Schadendatum']]
df13

,Unnamed: 0,Verwendungszweck,Zendesk Ticket,Provider-ID,Schadennummer,von TPA erhalten,Risikobelegenheit,Sitz des Händlers,Grund des Rückerhaltes von TPA,Produktbezeichnung,...,Schadenbearbeitungskosten,insurance_provider,Fallart,Zendesk Ticket Status,Auszahlung_Datev,DifferenceRisk,Differencevertrag,Diff_risk_end_start_Error(zendesk),Diff_vertrag_end_start_Error(zendesk),Duplicate_zendesk_in table
22,22,S-I000013273822930721002/81824/MDR2 127326,81824,NaN,81824I000013273822930721002,hepster reguliert,DE,DE,NaN,Restschuld,...,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,closed,-2601.61,915,1095,NaN,NaN,NaN
74,74,S-I0000120725739450421008/72578/MDR 2125756,72578,NaN,72578I0000120725739450421008,hepster reguliert,DE,DE,NaN,Restschuld,...,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,solved,-1354.40,915,1095,NaN,NaN,NaN
94,94,I0000110018318871120002/68420,68420,NaN,68420I0000110018318871120002,hepster reguliert,DE,DE,NaN,Restschuld,...,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,closed,-3379.90,915,1095,NaN,NaN,NaN
142,142,NaN,81660,NaN,81660I0000114781307090721079,NaN,DE,DE,NaN,Restschuld,...,NaN,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,hold,NaN,915,1095,NaN,NaN,NaN
144,144,EREF+4134253100-0000001KREF+4134253100SVWZ+RNr...,55916,NaN,55916I000012953919911219002,hepster reguliert,DE,NaN,NaN,Restschuld,...,5.0,LV 1871 Private Assurance AG,schaden__auszahlung__schaden,closed,-938.82,915,1095,NaN,NaN,NaN

In [42]:
df13.to_excel('datedif2.xlsx')

In [43]:
df5= pd.read_excel('datedif2.xlsx')
df12["Schadenmeldung_schadendatum_falseinfo[check following zendesk"] = df5["Zendesk Ticket"]

In [44]:
#highlighting the missing values
df12= df12.style.highlight_null('orange')

In [45]:
df12.to_excel('finalformLV1871claims.xlsx')

In [46]:
df12